version: '3'

services:
  hydra:
    image: oryd/hydra:v1.0.0-beta.9
    #    ports:
    #      - "4444:4444"
    #      - "4445:4445"
    #      - "4446:4446"
    environment:
      - OAUTH2_SHARE_ERROR_DEBUG=1
      - LOG_LEVEL=debug
      - OAUTH2_CONSENT_URL=https://192.168.142.1:4447/consent
      - OAUTH2_LOGIN_URL=https://192.168.142.1:4447/login
      - OAUTH2_ISSUER_URL=https://192.168.142.1:4444
      - DATABASE_URL=memory
      - SYSTEM_SECRET=7720265ad75cbc30bae9f45ec720ec7eda1c54c67dc0e1655de32f54492278ee
      - HTTPS_ALLOW_TERMINATION_FROM=172.17.0.0/24
    command: |
     serve all --dangerous-force-http

  hydra_ui:
    image: node:alpine
    #    ports:
    #      - "4447:4447"
    command: |
      yarn start
    environment:
    - HYDRA_ADMIN_URL=http://172.17.0.1:4445
    volumes:
    - $PWD/hydra-login-consent-node:/work
    working_dir: /work

  revproxy:
    image: nginx:alpine
    ports:
      - "3300:3300"
      - "4444:4444"
      - "4445:4445"
      - "4446:4446"
      - "4447:4447"
    volumes:
    - $PWD/server.crt:/etc/server.crt
    - $PWD/server.key:/etc/server.key
    - $PWD/default.conf:/etc/nginx/conf.d/default.conf
